name: my_plant_flutter
description: "Project created for postgraduate mobile application development - hybrid development"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Bebas Neue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
